#=========================================================
#   ___   ___   ________  _________  _________  __  __    
#  /___/\/__/\ /_______/\/________/\/________/\/_/\/_/\   
#  \::.\ \\ \ \\__.::._\/\__.::.__\/\__.::.__\/\ \ \ \ \  
#   \:: \/_) \ \  \::\ \    \::\ \     \::\ \   \:\_\ \ \ 
#    \:. __  ( (  _\::\ \__  \::\ \     \::\ \   \::::_\/ 
#     \: \ )  \ \/__\::\__/\  \::\ \     \::\ \    \::\ \ 
#      \__\/\__\/\________\/   \__\/      \__\/     \__\/ 
#=========================================================

# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts

font_family      Space Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

#: Font size (in pts)

font_size           11.0
force_ltr           yes

#: Performance tuning

repaint_delay    10
input_delay      2
sync_to_monitor  yes
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 3.0

#: Cursor

cursor_shape           underline
cursor_beam_thickness  1.5
cursor_blink_interval -1
mouse_hide_wait        3.0

#: Bell

visual_bell_duration  0.5
enable_audio_bell     yes
bell_on_tab           "🔔 "

#: Tab bar

tab_bar_edge      bottom
tab_bar_style     powerline
#tab_bar_aling    left
inactive_text_alpha       0.4
inactive_tab_background #3c3f43
active_tab_background   #68dcda
inactive_tab_foreground #000000
inactive_border_color   #585858
active_border_color     #00aaff

#: URLs

detect_urls         yes
url_style           double
open_url_modifiers  ctrl+shift
open_url_with       firefox-developer-edition
copy_on_select      yes

#: Window layout

remember_window_size      no
initial_window_width      950
initial_window_height     400
window_resize_step_cells  2
window_resize_step_lines  2
window_padding_width      13

#: OS specific tweaks

shell                   .
editor                  .
shell_integration       enable
shell_integration       no-cursor
#wayland_titlebar_color  system
linux_display_server    auto
#hide_window_decorations no
enabled_layouts         *
close_on_child_death    no
focus_follows_mouse     yes
copy_on_select          yes

#: Keys

#: Copy and paste
map ctrl+v              paste_from_clipboard
map ctrl+c              copy_to_clipboard
map ctrl+shift+v        paste_from_selection
#map shift+insert        paste_from_selection

#: Scroll
map ctrl+shift+k        scroll_line_up
map ctrl+shift+j        scroll_line_down

#: Change to space in the instance
map ctrl+shift+left    neighboring_window left
map ctrl+shift+right   neighboring_window right
map ctrl+shift+up      neighboring_window up
map ctrl+shift+down    neighboring_window down

#: New space, new instance and clows instance
map ctrl+shift+enter   new_window_with_cwd
map ctrl+shift+n       new_os_window
map ctrl+shift+w       close_window

#: Font zoom
map ctrl++             increase_font_size
map ctrl+-             decrease_font_size
map ctrl+space         restore_font_size

#: Zoom space and rename tab
map ctrl+shift+z       toggle_layout stack
map ctrl+alt+t         set_tab_title

#: Resize spacings
map ctrl+alt+left     resize_window wider
map ctrl+alt+right    resize_window narrower
map ctrl+alt+up       resize_window taller
map ctrl+alt+down     resize_window shorter
map ctrl+alt+space    resize_window reset

#: Tbas (move and goto tob)
map ctrl+shift+j move_tab_backward
map ctrl+shitf+k move_tab_forward
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

#: Theme

background_opacity          0.80
#dynamic_background_opacity  yes
include ./themes/Atom.conf