#!/usr/bin/sh
#=====================================================================================
#    '##::::'##:'##:::'##::::'########:::'######::'########::'##:::::'##:'##::::'##:  
#     ###::'###:. ##:'##::::: ##.... ##:'##... ##: ##.... ##: ##:'##: ##: ###::'###:  
#     ####'####::. ####:::::: ##:::: ##: ##:::..:: ##:::: ##: ##: ##: ##: ####'####:  
#     ## ### ##:::. ##::::::: ########::. ######:: ########:: ##: ##: ##: ## ### ##:  
#     ##. #: ##:::: ##::::::: ##.... ##::..... ##: ##.....::: ##: ##: ##: ##. #: ##:  
#     ##:.:: ##:::: ##::::::: ##:::: ##:'##::: ##: ##:::::::: ##: ##: ##: ##:.:: ##:  
#     ##:::: ##:::: ##::::::: ########::. ######:: ##::::::::. ###. ###:: ##:::: ##:  
#   ..:::::..:::::..::::::::........::::......:::..::::::::::...::...:::..:::::..::   
#=====================================================================================

#start
sxhkd &
picom -b &
dunst &
xsetroot -cursor_name left_ptr &

# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#To adjust to the resolution of my laptop
#xrandr -s 1360x768 &

#xrandr -s 1920x1080 &
#xrandr -s 2048x1080 &
#xrandr -s 3840 x 2160 &

#set wallpaper
#feh --bg-fill $HOME/Pictures/Your-wallpaper.jpg
feh --bg-fill $HOME/.config/bspwm/img_1.jpg

#set polybar
$HOME/.config/polybar/poly1/launch.sh &
#$HOME/.config/polybar/poly2/launch.sh &
#$HOME/.config/polybar/poly3/launch.sh &

#monitor´s
#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d 一 二 三 四 五 六 七 八 九
#bscp monitor -d 1 2 3 4 5 6 7 8 9

# monitores
#bscp monitor eDP-1 center
#bscp monitor HDMI-A-0 left
#bspc monitor left -d 1 2 3 4 5 6 7 8 9

#Theme for bspwm -Custom-
bspc config normal_border_color "#000000"
#bspc config active_border_color "#676767"
bspc config focused_border_color "#8E093B"
bspc config presel_feedback_color "#a7fbff"

#Gaps
bspc config border_width         3.7
bspc config window_gap           10

bspc config automatic_scheme      spiral
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config focused_frame_opacity 0.5
bspc config normal_frame_opacity  1
#bspc config border_radius         9.0

# Rules
#bscp rule -a polybar manage=off
#bscp rule -a firefoxdeveloperedition Desktop='^2'
#bscp rule -a Spotify Desktop='^5'

# -- flotantes --
bspc rule -a "WM_CLASS=gnome-calculator" state=floating

#Enable touchpad gestures       
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
