#!/usr/bin/sh
#=====================================================================================
#    '##::::'##:'##:::'##::::'########:::'######::'########::'##:::::'##:'##::::'##:  
#     ###::'###:. ##:'##::::: ##.... ##:'##... ##: ##.... ##: ##:'##: ##: ###::'###:  
#     ####'####::. ####:::::: ##:::: ##: ##:::..:: ##:::: ##: ##: ##: ##: ####'####:  
#     ## ### ##:::. ##::::::: ########::. ######:: ########:: ##: ##: ##: ## ### ##:  
#     ##. #: ##:::: ##::::::: ##.... ##::..... ##: ##.....::: ##: ##: ##: ##. #: ##:  
#     ##:.:: ##:::: ##::::::: ##:::: ##:'##::: ##: ##:::::::: ##: ##: ##: ##:.:: ##:  
#     ##:::: ##:::: ##::::::: ########::. ######:: ##::::::::. ###. ###:: ##:::: ##:  
#   ..:::::..:::::..::::::::........::::......:::..::::::::::...::...:::..:::::..::   
#=====================================================================================

# Start
sxhkd &
picom -b &
dunst &
xsetroot -cursor_name left_ptr &

# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#To adjust to the resolution of my laptop
#xrandr -s 1360x768 &

#xrandr -s 1920x1080 &
#xrandr -s 2048x1080 &
#xrandr -s 3840 x 2160 &

# Set wallpaper
#feh --bg-fill $HOME/Pictures/Your-wallpaper.jpg
feh --bg-fill $HOME/.config/bspwm/img_1.jpg

# Set polybar
$HOME/.config/polybar/poly1/launch.sh &
#$HOME/.config/polybar/poly2/launch.sh &
#$HOME/.config/polybar/poly3/launch.sh &
#$HOME/.config/polybar/poly4/launch.sh &

# Dunst notification
$HOME/.config/dunst/scripts/baterry_alert.sh &

# Monitor's
#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d 一 二 三 四 五 六 七 八 九
#bscp monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d 󰎦 󰎩 󰎬 󰎮 󰎰 󰎵 󰎸 󰎻 󰎾

# Monitor's
#bscp monitor eDP-1 center
#bscp monitor HDMI-A-0 left
#bspc monitor left -d 1 2 3 4 5 6 7 8 9

# Theme for bspwm -Custom-
bspc config normal_border_color "#000000"
bspc config focused_border_color "#8E093B"
bspc config presel_feedback_color "#a7fbff"

# Gaps
bspc config border_width         2.7
bspc config window_gap           7

#SPACES=$(bspc query -D)
#for SPACE in $SPACES
#do
#  bspc config -d $SPACE window_gap      5
#  bspc config -d $SPACE top_padding     2
#  bspc config -d $SPACE left_padding    5
#  bspc config -d $SPACE right_padding   5
#  bspc config -d $SPACE bottom_padding  2
#done

bspc config automatic_scheme      spiral
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config focused_frame_opacity 0.5
bspc config normal_frame_opacity  1
bspc config border_radius         16.0

# Rules
#bscp rule -a polybar manage=off
#bscp rule -a firefoxdeveloperedition desktop='^3'
bspc rule -a "spotify" desktop='^9'

# -- float's --
bspc rule -a "WM_CLASS=gnome-calculator" state=floating
bspc rule -a "gnome-calculator" state=floating
bspc rule -a "WM_CLASS=Gnome-screenshot" state=floating
bspc rule -a "Gnome-screenshot" state=floating

# Touchpad
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
