;
;; Theme Cherry
;

[base]
default           = none
unknown-token     = 196,bold,standout
secondary         = sv-orple
recursive-base    = 183
sudo              = 202,bold,underline
rm                = white,bg=160,bold


[background]
correct-subtle   = bg:18
incorrect-subtle = bg:238
subtle-bg        = bg:17
global-alias     = bg:20,bold

;;
;; COLOR-GROUPS
;;

[gray]
comment = 243


[pastel]
here-string-tri        = 217


[no-color]
assign               = none
back-quoted-argument = none
redirection          = none
variable             = none



[magenta-3]
dollar-quoted-argument = 173
double-quoted-argument = 173
history-expansion      = 173
globbing-ext           = 173
precommand             = 173

[light-salmon-3]
builtin                = 137
subcommand             = 137
single-quoted-argument = 137

[steel-blue-3]
command           = 68,bold
double-sq-bracket = 68
double-paren      = 68
single-sq-bracket = 68

[steel-blue]
reserved-word          = 67,bold


[medium-purple]
; backslash in $'...'
back-dollar-quoted-argument  = 104
commandseparator             = 104
single-hyphen-option         = 104,bold,underline


[dark-khaki]
double-hyphen-option   = 143


[hot-pink-3]
alias              = 168,bold
exec-descriptor    = 168
function           = 168
hashed-command     = 168
here-string-var    = 168
suffix-alias       = 168,bold,underline


[pale-green-3]
assign-array-bracket                  = 114
; variable $... or backslash in "..." (i.e. variable in string)
back-or-dollar-double-quoted-argument = 114
globbing                              = 114
here-string-text                      = 114


[orchid]
path                   = 170,bold,underline
path-to-dir            = 170,bold,underline
pathseparator          = 


;;
;; FUNCTIONALITY-GROUPS
;;

[brackets]
paired-bracket = black,bg:216
bracket-level-1 = 117
bracket-level-2 = 217
bracket-level-3 = 220

[math]
mathvar = 68
mathnum = 173
matherr = 124

[for-loop]
forvar = 68
fornum = 173
; operator
foroper = 133
; separator
forsep = 104

[case]
case-input       = 168
case-parentheses = 217
case-condition   = bg:25
